# Generated by Django 5.0.2 on 2024-03-25 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('courseID', models.CharField(max_length=9, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('studentName', models.CharField(max_length=64)),
                ('studentID', models.IntegerField(primary_key=True, serialize=False)),
                ('studentGPA', models.FloatField(max_length=3)),
                ('courses', models.ManyToManyField(blank=True, related_name='student_courses', to='theLab.courses')),
            ],
        ),
    ]
