# Generated by Django 5.0.2 on 2024-03-25 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theLab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='studentPN',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
