# Generated by Django 5.0.2 on 2024-03-25 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theLab', '0002_students_studentpn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='studentPN',
            new_name='studentPhoneNumber',
        ),
    ]
